name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    name: Terraform - ${{ inputs.environment }}
    runs-on: ubuntu-latest

    env:
      TF_VAR_public_key: ${{ secrets.EC2_PUBLIC_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Verify Checked Out Code
        run: |
          echo "Commit SHA:"
          git rev-parse HEAD

          echo "Latest commit:"
          git log -1 --oneline

          echo "Key pair block:"
          grep -A8 'resource "aws_key_pair"' modules/ec2/main.tf

          echo "Checking old public_key_path:"
          grep -R --exclude-dir=.terraform "public_key_path" modules environments || true

      - name: Terraform Init
        run: terraform -chdir=environments/${{ inputs.environment }} init

      - name: Terraform Format Check
        run: terraform -chdir=environments/${{ inputs.environment }} fmt -check

      - name: Terraform Validate
        run: terraform -chdir=environments/${{ inputs.environment }} validate

      - name: Terraform Plan
        run: terraform -chdir=environments/${{ inputs.environment }} plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=environments/${{ inputs.environment }} apply -auto-approve tfplan

      - name: Terraform Output
        run: terraform -chdir=environments/${{ inputs.environment }} output